### ISSUE TITLE
Makefile question

### ISSUE THREAD

**Issue by sebastian-luna-valero** [student-t/Anaquin#1]
Hello,

I am trying to include anaquin as a bioconda page:
https://bioconda.github.io

However, I am running into problems and would like to ask for help. 

To make your program portable, I am tweaking the Makefile and right now this is what I have:
```
CC = g++
CC_FLAGS = -std=c++11

EXEC         = anaquin
SOURCES      = $(wildcard src/*.cpp src/tools/*.cpp src/analyzers/*.cpp src/RnaQuin/*.cpp src/VarQuin/*.cpp src/MetaQuin/*.cpp src/data/*.cpp src/parsers/*.cpp src/writers/*.cpp src/stats/*.cpp src/cufflinks/*.cpp)
OBJECTS      = $(SOURCES:.cpp=.o)
OBJECTS_TEST = $(SOURCES_TEST:.cpp=.o)
SOURCES_LIB  = $(wildcard src/htslib/*.c src/htslib/cram/*.c)
OBJECTS_LIB  = $(SOURCES_LIB:.c=.o)

$(EXEC): $(OBJECTS) $(OBJECTS_TEST) $(OBJECTS_LIB)
	$(CC) $(OBJECTS) $(OBJECTS_TEST) $(OBJECTS_LIB) -L $(VCFLIB) -g -lpthread -lz -lvcflib -o $(EXEC)

%.o: %.c
	gcc -c -I src/htslib -I $(INCLUDE) -I $(EIGEN) -I ${BOOST} -I ${KLIB} $< -o $@

%.o: %.cpp
	$(CC) -g -DK_HACK -c $(CC_FLAGS) -I src/htslib -I $(VCFLIB) -I src/stats -I $(INCLUDE) -I $(EIGEN) -I ${BOOST} -I ${KLIB} $< -o $@
	
clean:
	rm -f $(EXEC) $(OBJECTS) $(OBJECTS_TEST)
```

The conda recipe is below.

When I build the package, I get:
```
make: *** No rule to make target `src/main.o', needed by `anaquin'.  Stop.
```

There must be something silly that I am missing, could you please let me know what?

Best regards,
Sebastian

----

build.sh
```
#!/bin/bash
set -eu -o pipefail

# download and copy required dependencies
# klib
wget https://github.com/attractivechaos/klib/archive/spawn-final.tar.gz
tar xzf spawn-final.tar.gz
cp -r $SRC_DIR/klib-spawn-final $PREFIX/lib/klib/

# vcflib
wget https://github.com/student-t/vcflib-forAnaquin/archive/v1.0.0-rc1.tar.gz
tar xzf v1.0.0-rc1.tar.gz
cp -r $SRC_DIR/vcflib-forAnaquin-1.0.0-rc1/src $PREFIX/lib/vcflib/

# clean Makefile
sed -i'' -e 's/^BOOST.*//g' Makefile
sed -i'' -e 's/^EIGEN.*//g' Makefile
sed -i'' -e 's/^KLIB.*//g' Makefile
sed -i'' -e 's/^VCFLIB.*//g' Makefile
sed -i'' -e 's/\/include//g' Makefile
sed -i'' -e 's/.*BACKWARD_HAS_BFD.*//g' Makefile
sed -i'' -e 's/^INCLUDE.*//g' Makefile

export CPPFLAGS="-I$PREFIX/include"
export LDFLAGS="-L$PREFIX/lib"

export INCLUDE="$SRC_DIR/src"
export BOOST="$PREFIX/include/boost"
export EIGEN="$PREFIX/include/eigen3"
export KLIB="$PREFIX/lib"
export VCFLIB="$PREFIX/lib"

make
```

meta.yml
```
{% set version = "1.1.0" %}

package:
  name: anaquin
  version: {{version}}

build:
  number: 0
  string: boost{{CONDA_BOOST}}_{{PKG_BUILDNUM}}
  skip: True # [osx]

source:
  fn: {{version}}.tar.gz
  url: https://github.com/student-t/Anaquin/archive/{{version}}.tar.gz
  md5: c989314e15198a49b6731d82e23b3272

requirements:
  build:
  - gcc  # [not osx]
  - llvm # [osx]
  - boost {{CONDA_BOOST}}*
  - eigen 3.3.1
  - gnu-wget

  run:
  - libgcc # [not osx]
  - boost {{CONDA_BOOST}}*
  - eigen 3.3.1

test:
  commands:
    - anaquin

about:
  home: http://www.sequin.xyz/software/
  license: BSD
  summary: Statistical analysis of sequins in C++
```
